### ISSUE TITLE
[Feature request] Collumn view

### ISSUE THREAD

**Issue by andercard0** [olvidalo/obsidian-chord-sheets#35]
Hi,

I'd like to request a 'collumn view' (in a lack of better name) as below:

Nowadays we can see chords/lyrics this way:

![Image](https://github.com/user-attachments/assets/47de201d-595d-41a1-acb6-1c1eb458a2c3)

Kind of leaving a huge space at the right side which, i believe, would be best utilized this way:

![Image](https://github.com/user-attachments/assets/7da5949b-25e7-465b-a87a-35bbabc997e8)

So if you can consider would be a great :)

**Comment by mattbowers** [comment]
Hi there, 

I have been using this CSS snippet as solution:

```css
/* Optional class for 2-column layout - add in frontmatter to enable */
.two-column pre {
  column-count: 2;
  column-fill: balance;
  }
```

...which can then be referenced in the frontmatter:

```
---
cssclasses: two-column
---
```

...to enable a two column view of a chordsheet.
